// constants/portfolioData.ts
export const portfolioData = {
  profile: {
    name: "Kumar Abhishek",
    username: "kabhishek18",
    title: "Full Stack Software Developer",
    subtitle: "Rich experience in Web & Mobile Application Development",
    email: "developer@kabhishek18.com",
    github: "https://github.com/kabhishek18",
    linkedin: "https://linkedin.com/in/kabhishek18",
    twitter: "https://twitter.com/kabhishek18",
    freelancer: "https://www.freelancer.com/u/kabhishek18",
    orcid: "https://orcid.org/0009-0006-6321-2424",
    phone: "+91 (705) 394-8103",
    whatsapp: "https://wa.me/7053948103",
    website: "https://kabhishek18.com",
    bio: "I'm an experienced Full Stack Software Developer with over 9 years of experience in Python, PHP, and ReactJS. I have rich experience in Web Application Development and Mobile Application Development, working across e-commerce, Aviation, and Edtech domains.",
    location: "India",
    experience: "9+ Years",
    availability: "Open to new opportunities",
    followers: 40,
    following: 33,
    achievements: ["Developer Program Member"],
  },

  stats: {
    experience: "9+",
    totalProjects: "50+",
    publicRepos: "35+",
    technologies: "20+",
    pypiPackages: "4",
    githubStars: "25+",
  },

  currentWork: {
    focus: "React Native (Android, iOS), Python Django",
    collaboration: "Looking to collaborate on projects relevant to my skills",
    askMeAbout: "Anything about my projects and full-stack development",
    specialization: "Web & Mobile Application Development",
  },

  recentProjects: [
    // PyPI Packages (Recent)
    {
      id: 1,
      title: "ChatMS Plugin",
      description: "A comprehensive chat messaging system plugin for Python applications with real-time communication features",
      technologies: ["Python", "WebSocket", "Real-time Chat"],
      githubUrl: "https://github.com/kabhishek18/chatms-plugin",
      pypiUrl: "https://pypi.org/project/chatms-plugin/",
      type: "PyPI Package",
      lastUpdated: "May 21, 2025",
      stars: 1,
      license: "MIT",
    },
    {
      id: 2,
      title: "Resume ATS Plugin",
      description: "A plugin to analyze and optimize resumes for Applicant Tracking Systems (ATS) with scoring and recommendations",
      technologies: ["Python", "NLP", "ATS Analysis"],
      githubUrl: "https://github.com/kabhishek18/resume-ats-plugin",
      pypiUrl: "https://pypi.org/project/resume-ats-plugin/",
      type: "PyPI Package",
      lastUpdated: "May 17, 2025",
      stars: 1,
      license: "MIT",
    },
    {
      id: 3,
      title: "Jitsi Plus Plugin",
      description: "Comprehensive Python integration for Jitsi Meet with video conferencing, audio calls, broadcasting, and VOD",
      technologies: ["Python", "Jitsi Meet API", "Video Conferencing"],
      githubUrl: "https://github.com/kabhishek18/jitsi-plugin",
      pypiUrl: "https://pypi.org/project/jitsi-plus-plugin/",
      type: "PyPI Package",
      lastUpdated: "May 14, 2025",
      stars: 1,
      license: "MIT",
    },
    {
      id: 4,
      title: "Magic Profanity",
      description: "A Python library for detecting and censoring profanity in text with customizable filters and language support",
      technologies: ["Python", "NLP", "Text Processing"],
      githubUrl: "https://github.com/kabhishek18/magic_profanity",
      pypiUrl: "https://pypi.org/project/magic-profanity/",
      type: "PyPI Package",
      lastUpdated: "May 13, 2025",
      stars: 1,
      license: "MIT",
    },
    {
      id: 5,
      title: "Deep Live Cam",
      description: "Real time face swap and one-click video deepfake with only a single image (Forked & Enhanced)",
      technologies: ["Python", "Computer Vision", "AI/ML"],
      githubUrl: "https://github.com/kabhishek18/Deep-Live-Cam",
      type: "Fork/Enhancement",
      lastUpdated: "3 weeks ago",
      license: "GNU AGPL v3.0",
    },
  ],

  allProjects: [
    // Web Applications
    {
      id: 6,
      title: "Django E-commerce Template",
      description: "Comprehensive e-commerce solution built with Django with complete shopping cart functionality",
      technologies: ["Django", "Python", "E-commerce", "CSS"],
      githubUrl: "https://github.com/kabhishek18/django_ecom_template",
      type: "Template",
      stars: 2,
      license: "The Unlicense",
      lastUpdated: "May 3, 2023",
    },
    {
      id: 7,
      title: "Resume Builder",
      description: "Django-based resume builder with multiple templates and PDF export functionality",
      technologies: ["Django", "Python", "PDF Generation"],
      githubUrl: "https://github.com/kabhishek18/resume_builder",
      type: "Web Application",
      stars: 3,
      lastUpdated: "Mar 13, 2023",
    },
    {
      id: 8,
      title: "Learning Management System",
      description: "Complete LMS platform for educational institutions with course management",
      technologies: ["HTML", "CSS", "JavaScript"],
      githubUrl: "https://github.com/kabhishek18/learn-management-system",
      type: "Web Application",
      stars: 2,
      license: "MIT",
      lastUpdated: "Apr 10, 2023",
    },
    {
      id: 9,
      title: "Developogram.com",
      description: "Developer community platform with project showcases and networking features",
      technologies: ["JavaScript", "Web Development"],
      githubUrl: "https://github.com/kabhishek18/developogram.com",
      type: "Platform",
      stars: 4,
      license: "GNU GPL v3.0",
      lastUpdated: "Apr 10, 2023",
    },

    // Mobile & React Projects
    {
      id: 10,
      title: "React Portfolio",
      description: "Professional portfolio website built with React and modern design principles",
      technologies: ["React", "JavaScript"],
      githubUrl: "https://github.com/kabhishek18/react-portfolio-kabhishek18",
      type: "Portfolio",
      stars: 1,
      license: "The Unlicense",
      lastUpdated: "May 18, 2023",
    },
    {
      id: 11,
      title: "React Goal Task Manager",
      description: "Basic goal setting and task management application built with React",
      technologies: ["React", "Task Management"],
      githubUrl: "https://github.com/kabhishek18/React-Goal-Task",
      type: "Web Application",
      stars: 2,
      lastUpdated: "Mar 20, 2023",
    },
    {
      id: 12,
      title: "React Material Admin",
      description: "Admin dashboard template using React and Material-UI components",
      technologies: ["React", "Material-UI", "Admin Panel"],
      githubUrl: "https://github.com/kabhishek18/react_material_admin",
      type: "Template",
      stars: 1,
      license: "MIT",
      lastUpdated: "Mar 19, 2023",
    },

    // Python & Data Science
    {
      id: 13,
      title: "Python Projects Collection",
      description: "Comprehensive collection of Python projects from beginner to advanced level",
      technologies: ["Python", "Jupyter Notebook", "Data Science"],
      githubUrl: "https://github.com/kabhishek18/python_project",
      type: "Educational",
      stars: 5,
      license: "The Unlicense",
      lastUpdated: "Apr 16, 2023",
    },
    {
      id: 14,
      title: "Handwriting Recognition",
      description: "Python-based handwriting recognition system using machine learning",
      technologies: ["Python", "Machine Learning", "Image Processing"],
      githubUrl: "https://github.com/kabhishek18/handwritingPython",
      type: "ML Project",
      stars: 1,
      license: "The Unlicense",
      lastUpdated: "Feb 19, 2023",
    },
    {
      id: 15,
      title: "Weather Web App",
      description: "Weather application with API integration and responsive design",
      technologies: ["Python", "API Integration", "Web Development"],
      githubUrl: "https://github.com/kabhishek18/weatherweb",
      type: "Web Application",
      stars: 1,
      lastUpdated: "Dec 10, 2022",
    },

    // Specialized Tools
    {
      id: 16,
      title: "Django Page Builder",
      description: "Dynamic page builder for Django applications with drag-and-drop functionality",
      technologies: ["Django", "JavaScript", "Page Builder"],
      githubUrl: "https://github.com/kabhishek18/Django_page_builder",
      type: "Tool",
      stars: 1,
      license: "GNU GPL v3.0",
      lastUpdated: "Last month",
    },
    {
      id: 17,
      title: "Django Mongo Template",
      description: "Basic template for MongoDB helper using JSON schema with Django integration",
      technologies: ["Django", "MongoDB", "JSON Schema"],
      githubUrl: "https://github.com/kabhishek18/django-mongo-template",
      type: "Template",
      stars: 1,
      license: "The Unlicense",
      lastUpdated: "Sep 23, 2023",
    },
    {
      id: 18,
      title: "Interview Project API",
      description: "RESTful API system designed for technical interview processes",
      technologies: ["Python", "API Development", "Interview System"],
      githubUrl: "https://github.com/kabhishek18/interviewproject",
      type: "API",
      stars: 1,
      lastUpdated: "Apr 21, 2024",
    },
  ],

  skills: [
    // Backend & Languages (Expert Level)
    { name: "Python", level: 95, category: "expert", icon: "🐍", years: "9+" },
    { name: "PHP", level: 90, category: "expert", icon: "🌐", years: "8+" },
    { name: "JavaScript", level: 88, category: "expert", icon: "⚡", years: "7+" },
    { name: "TypeScript", level: 80, category: "expert", icon: "📘", years: "5+" },

    // Frameworks & Libraries (Expert)
    { name: "Django", level: 95, category: "expert", icon: "🎯", years: "9+" },
    { name: "React", level: 85, category: "expert", icon: "⚛️", years: "6+" },
    { name: "React Native", level: 90, category: "expert", icon: "📱", years: "5+" },
    { name: "CodeIgniter", level: 88, category: "expert", icon: "🔥", years: "7+" },

    // Databases (Intermediate/Expert)
    { name: "MongoDB", level: 85, category: "expert", icon: "🍃", years: "6+" },
    { name: "PostgreSQL", level: 80, category: "intermediate", icon: "🐘", years: "5+" },
    { name: "MySQL", level: 88, category: "expert", icon: "🗄️", years: "8+" },

    // Tools & Technologies
    { name: "Node.js", level: 75, category: "intermediate", icon: "🟢", years: "4+" },
    { name: "Docker", level: 70, category: "intermediate", icon: "🐳", years: "3+" },
    { name: "Git", level: 90, category: "expert", icon: "📝", years: "9+" },
    { name: "AWS", level: 65, category: "intermediate", icon: "☁️", years: "3+" },
    { name: "Redis", level: 70, category: "intermediate", icon: "🔴", years: "4+" },

    // Specialized
    { name: "API Development", level: 92, category: "expert", icon: "🔌", years: "8+" },
    { name: "WebSocket", level: 85, category: "expert", icon: "🔗", years: "5+" },
    { name: "PyPI Publishing", level: 90, category: "expert", icon: "📦", years: "2+" },
    { name: "Machine Learning", level: 70, category: "intermediate", icon: "🤖", years: "3+" },
  ],

  domains: [
    { name: "E-commerce", experience: "7+ years", icon: "🛒", projects: 12 },
    { name: "Aviation", experience: "4+ years", icon: "✈️", projects: 5 },
    { name: "EdTech", experience: "5+ years", icon: "🎓", projects: 8 },
    { name: "Web Applications", experience: "9+ years", icon: "🌐", projects: 25 },
    { name: "Mobile Apps", experience: "6+ years", icon: "📱", projects: 10 },
    { name: "API Development", experience: "8+ years", icon: "🔌", projects: 20 },
  ],

  achievements: [
    {
      title: "Developer Program Member",
      description: "Recognized member of developer community programs",
      icon: "🏆",
      date: "2024",
    },
    {
      title: "4 PyPI Packages Published",
      description: "Successfully published and maintained Python packages",
      icon: "📦",
      date: "2025",
    },
    {
      title: "50+ Open Source Projects",
      description: "Contributed to open source community with various projects",
      icon: "🌟",
      date: "2024",
    },
    {
      title: "9+ Years Experience",
      description: "Nearly a decade of professional software development",
      icon: "⏰",
      date: "2024",
    },
  ],

  socialLinks: [
    { platform: "GitHub", url: "https://github.com/kabhishek18", icon: "logo-github", color: "#333" },
    { platform: "LinkedIn", url: "https://linkedin.com/in/kabhishek18", icon: "logo-linkedin", color: "#0A66C2" },
    { platform: "Twitter", url: "https://twitter.com/kabhishek18", icon: "logo-twitter", color: "#1DA1F2" },
    { platform: "Freelancer", url: "https://www.freelancer.com/u/kabhishek18", icon: "briefcase", color: "#00b4d8" },
    { platform: "ORCID", url: "https://orcid.org/0009-0006-6321-2424", icon: "school", color: "#A6CE39" },
    { platform: "Website", url: "https://kabhishek18.com", icon: "globe", color: "#FF6B35" },
  ],
};